/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UAccordion: typeof import('./node_modules/.pnpm/@nuxt+ui@3.0.2_@babel+parse_857c2ab097445824539c6e2a28a13196/node_modules/@nuxt/ui/dist/runtime/components/Accordion.vue')['default']
    UApp: typeof import('./node_modules/.pnpm/@nuxt+ui@3.0.2_@babel+parse_857c2ab097445824539c6e2a28a13196/node_modules/@nuxt/ui/dist/runtime/components/App.vue')['default']
    UButton: typeof import('./node_modules/.pnpm/@nuxt+ui@3.0.2_@babel+parse_857c2ab097445824539c6e2a28a13196/node_modules/@nuxt/ui/dist/runtime/components/Button.vue')['default']
    ULinkBase: typeof import('./node_modules/.pnpm/@nuxt+ui@3.0.2_@babel+parse_857c2ab097445824539c6e2a28a13196/node_modules/@nuxt/ui/dist/runtime/components/LinkBase.vue')['default']
  }
}
